// PDF export — A4 portrait, 2 pages (spec §12)
//
// Both pages are composed from rasterized HTML/SVG images. This sidesteps
// jsPDF's core-font limitation (no Thai glyphs): the page-1 report is
// rendered as an image using the site's Noto Sans Thai font, and page 2 is
// the captured Gantt. Flagged per spec §12 ("embed as image in PDF").

import type { Phase, ProjectConfig } from "../types";
import { formatThaiDate } from "../date-format";
import { countWorkingDays } from "../date-utils";
import { getThaiHolidaysInRange } from "../thai-holidays";
import { captureNodeToPng, htmlStringToPng } from "./png-export";
import { triggerDownload } from "./excel-export";

const A4 = { w: 595.28, h: 841.89 };
const MARGIN = 32;
const CONTENT_W = A4.w - MARGIN * 2;
const CONTENT_H = A4.h - MARGIN * 2;

function esc(s: string): string {
  return s.replace(/[&<>]/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : "&gt;",
  );
}

function fileDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate(),
  ).padStart(2, "0")}`;
}

function reportHtml(
  phases: Phase[],
  config: ProjectConfig,
  stats: {
    minStart: Date;
    maxEnd: Date;
    workingDays: number;
    holidayCount: number;
    phaseCount: number;
    taskCount: number;
    calendarDays: number;
  },
): string {
  const tasks = phases.flatMap((p) => p.tasks);
  let n = 0;
  const seq = new Map<string, number>();
  for (const t of tasks) seq.set(t.id, ++n);
  const rows = tasks
    .slice(0, 50)
    .map((t) => {
      const i = seq.get(t.id);
      return `<tr>
        <td style="padding:4px 6px;border-bottom:1px solid #e3e9f0;color:#54657a">${i}</td>
        <td style="padding:4px 6px;border-bottom:1px solid #e3e9f0">${esc(t.name)}</td>
        <td style="padding:4px 6px;border-bottom:1px solid #e3e9f0;text-align:center">${t.duration}</td>
        <td style="padding:4px 6px;border-bottom:1px solid #e3e9f0;white-space:nowrap">${t.startDate ? formatThaiDate(t.startDate) : "—"}</td>
        <td style="padding:4px 6px;border-bottom:1px solid #e3e9f0;white-space:nowrap">${t.endDate ? formatThaiDate(t.endDate) : "—"}</td>
      </tr>`;
    })
    .join("");
  const more =
    tasks.length > 50
      ? `<p style="margin:8px 0 0;font-size:12px;color:#54657a">… และอีก ${tasks.length - 50} tasks (ดูทั้งหมดในไฟล์ Excel)</p>`
      : "";
  const stat = (label: string, value: string) =>
    `<div style="border:1px solid #e3e9f0;border-radius:8px;padding:8px 12px">
      <div style="font-size:11px;color:#54657a">${label}</div>
      <div style="font-size:15px;font-weight:700;color:#0a2540">${value}</div>
    </div>`;
  return `<div style="padding:24px;font-size:13px;color:#0a2540">
    <div style="background:#0a2540;color:#fff;border-radius:10px;padding:16px 20px;display:flex;justify-content:space-between;align-items:center">
      <div>
        <div style="font-size:20px;font-weight:800">${esc(config.name || "โปรเจกต์ใหม่")}</div>
        <div style="font-size:12px;opacity:.8">Project Timeline · Software PM Tools</div>
      </div>
      <div style="font-size:12px;opacity:.8;text-align:right">สร้างเมื่อ<br/>${formatThaiDate(new Date())}</div>
    </div>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0">
      ${stat("วันทำการรวม", `${stats.workingDays} วัน`)}
      ${stat("วันเริ่ม", formatThaiDate(stats.minStart))}
      ${stat("วันสิ้นสุด", formatThaiDate(stats.maxEnd))}
      ${stat("จำนวน Phase", String(stats.phaseCount))}
      ${stat("จำนวน Task", String(stats.taskCount))}
      ${stat("วันตามปฏิทิน", `${stats.calendarDays} วัน`)}
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:12px">
      <thead><tr style="background:#f4f7fa;text-align:left">
        <th style="padding:6px">#</th><th style="padding:6px">Task</th>
        <th style="padding:6px;text-align:center">วันทำการ</th>
        <th style="padding:6px">เริ่ม</th><th style="padding:6px">สิ้นสุด</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>
    ${more}
    <p style="margin-top:24px;font-size:11px;color:#8a99a9;text-align:center">
      Generated by softwarepmtools.com on ${formatThaiDate(new Date())}
    </p>
  </div>`;
}

function holidaysHtml(holidays: { date: Date; name: string }[]): string {
  if (holidays.length === 0)
    return `<div style="padding:12px;font-size:12px;color:#54657a">ไม่มีวันหยุดราชการในช่วงโปรเจกต์</div>`;
  const items = holidays
    .map(
      (h) =>
        `<li style="margin:2px 0">${formatThaiDate(h.date)} — ${esc(h.name)}</li>`,
    )
    .join("");
  return `<div style="padding:12px;font-size:12px;color:#0a2540">
    <div style="font-weight:700;margin-bottom:6px">วันหยุดในช่วงโปรเจกต์ (${holidays.length})</div>
    <ul style="margin:0;padding-left:18px;columns:2">${items}</ul>
  </div>`;
}

/** Place an image into the PDF scaled to fit a box, returns drawn height. */
function fitImage(
  pdf: import("jspdf").jsPDF,
  dataUrl: string,
  imgW: number,
  imgH: number,
  boxW: number,
  boxH: number,
  x: number,
  y: number,
): number {
  const scale = Math.min(boxW / imgW, boxH / imgH);
  const w = imgW * scale;
  const h = imgH * scale;
  pdf.addImage(dataUrl, "PNG", x + (boxW - w) / 2, y, w, h);
  return h;
}

export async function exportTimelinePdf(
  ganttNode: HTMLElement,
  phases: Phase[],
  config: ProjectConfig,
): Promise<string> {
  const tasks = phases.flatMap((p) => p.tasks);
  const starts = tasks.map((t) => t.startDate).filter(Boolean) as Date[];
  const ends = tasks.map((t) => t.endDate).filter(Boolean) as Date[];
  const minStart =
    starts.length > 0
      ? new Date(Math.min(...starts.map((d) => +d)))
      : config.startDate;
  const maxEnd =
    ends.length > 0 ? new Date(Math.max(...ends.map((d) => +d))) : minStart;
  const holidays = config.includeThaiHolidays
    ? getThaiHolidaysInRange(minStart, maxEnd)
    : [];
  const stats = {
    minStart,
    maxEnd,
    workingDays: countWorkingDays(minStart, maxEnd, config),
    holidayCount: holidays.length,
    phaseCount: phases.length,
    taskCount: tasks.length,
    calendarDays:
      Math.round((maxEnd.getTime() - minStart.getTime()) / 86400000) + 1,
  };

  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "a4" });

  // ── Page 1: report ──
  const page1 = await htmlStringToPng(
    reportHtml(phases, config, stats),
    760,
  );
  fitImage(
    pdf,
    page1.dataUrl,
    page1.width,
    page1.height,
    CONTENT_W,
    CONTENT_H,
    MARGIN,
    MARGIN,
  );

  // ── Page 2: Gantt + holidays ──
  pdf.addPage();
  const gantt = await captureNodeToPng(ganttNode);
  const img = new Image();
  await new Promise<void>((res, rej) => {
    img.onload = () => res();
    img.onerror = () => rej(new Error("gantt image load failed"));
    img.src = gantt;
  });
  const holiImg = await htmlStringToPng(holidaysHtml(holidays), 720);
  const holiBoxH = 140;
  const ganttDrawn = fitImage(
    pdf,
    gantt,
    img.naturalWidth,
    img.naturalHeight,
    CONTENT_W,
    CONTENT_H - holiBoxH - 12,
    MARGIN,
    MARGIN,
  );
  fitImage(
    pdf,
    holiImg.dataUrl,
    holiImg.width,
    holiImg.height,
    CONTENT_W,
    holiBoxH,
    MARGIN,
    MARGIN + ganttDrawn + 12,
  );

  const filename = `timeline-${fileDate(new Date())}.pdf`;
  triggerDownload(pdf.output("blob"), filename);
  return filename;
}
